In [1]:
import numpy as np




In [2]:
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..')))

In [3]:
from utils.helpers import load_train_data, load_test_data, create_csv_submission


In [4]:
# x_train, x_test, y_train, train_ids, test_ids= load_csv_data("/home/dimgor/Рабочий стол/projects/epfl-ml2024-proj-1/dataset")
x_train, y_train = load_train_data('dataset')
x_test, test_ids= load_test_data('dataset')

In [5]:
kek = y_train.copy()


In [6]:
kek[kek == -1] = 0

In [7]:
def logistic_regression(y, tx, initial_w, max_iters, gamma):
    """Logistic regression using gradient descent. (y in {-1, 1})
    """
    def stable_sigmoid(t):
        """Numerically stable sigmoid function."""
        return np.where(t >= 0, 
                    1 / (1 + np.exp(-t)), 
                    np.exp(t) / (1 + np.exp(t)))

    w = initial_w
    for _ in range(max_iters):
        print(42)
        pred = tx @ w
        weights = np.where(y == 1, 11, 1)
        gradient = -tx.T @ (y * weights * stable_sigmoid(-y * pred)) / len(y)
        w = w - gamma * gradient
    # Compute the final loss
        loss = np.sum(weights * np.log(1 + np.exp(-y * (tx @ w)))) / len(y)
        print(loss)
        #if loss < 1:
         #   break

    return w, loss


In [8]:
x_kek = np.nan_to_num(x_train)
x_orb = np.nan_to_num(x_test)
x_orb -= np.min(x_kek,axis=0)
x_kek -= np.min(x_kek,axis=0)
quant = np.quantile(x_kek,0.9,axis=0)
x_kek = np.minimum(x_kek, quant)
x_orb = np.minimum(x_orb, quant)
x_kek /= (quant+0.01)
x_orb /= (quant+0.01)

In [9]:
x_orb

array([[0.85982803, 0.0999001 , 0.10479913, ..., 0.49751244, 0.49751244,
        0.99502488],
       [0.51989602, 0.        , 0.01762968, ..., 0.        , 0.        ,
        0.99502488],
       [0.67986403, 0.3996004 , 0.41625851, ..., 0.49751244, 0.49751244,
        0.99502488],
       ...,
       [0.15996801, 0.999001  , 1.        , ..., 0.99502488, 0.99502488,
        0.        ],
       [0.27994401, 0.999001  , 1.        , ..., 0.49751244, 0.49751244,
        0.99502488],
       [0.87982404, 0.999001  , 1.        , ..., 0.        , 0.        ,
        0.99502488]])

In [10]:

quant = np.quantile(x_kek,0.2,axis=0)

In [11]:
x_kek = np.nan_to_num(x_train)
x_orb = np.nan_to_num(x_test)
quant = np.quantile(x_kek,0.2,axis=0)


In [12]:
#np.quantile(x_kek,0.7, axis=0)

In [13]:
x_kek = np.nan_to_num(x_train)

np.quantile(x_kek,0.7,axis=1)

array([2., 1., 2., ..., 2., 2., 2.])

In [14]:
pos = sum(y_train == 1)
neg = len(y_train) - pos
print(pos,neg)
y_true = (y_train == 1)
x_train_new = np.concatenate([x_train] + [x_train[y_true]] * 10)
y_train_new = np.concatenate([y_train] + [y_train[y_true]] * 10)

28975 299160


: 

In [15]:
x_kek_new = np.nan_to_num(x_train_new)
x_kek_new[x_kek_new > 10] = 10


In [407]:
arr = np.corrcoef(x_kek,rowvar=False)
bad = []
good = []
for i in range(arr.shape[0]):
    ok = True
    for j in range(i):
        if i != j and abs(arr[i][j]) > 0.8:
            ok = False
    if ok:
        good.append(i)
    else:
        bad.append(i)
print(good)

[0, 1, 4, 5, 6, 7, 9, 11, 14, 22, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 99, 100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 194, 195, 196, 197, 198, 200, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 217, 218, 220, 223, 227, 230, 231, 234, 236, 239, 241, 242, 246, 250, 252, 255, 262, 263, 266, 267, 268, 269, 270, 271, 272, 273, 274, 277, 278, 280, 281, 282, 286, 293,

In [367]:
print(bad)

[3, 8, 10, 12, 15, 18, 19, 20, 21, 23, 24, 35, 41, 49, 54, 75, 96, 97, 108, 126, 181, 193, 199, 201, 202, 216, 219, 222, 224, 225, 226, 228, 232, 233, 235, 237, 238, 244, 247, 248, 249, 251, 254, 256, 257, 275, 279, 283, 287, 288, 290, 292, 299, 300, 306, 307, 308, 309, 310, 311, 312, 314, 318, 319, 320]


In [384]:
x_kek_new = x_kek
# -*- coding: utf-8 -*-
"""implement a polynomial basis function."""

import numpy as np


def build_poly(x, degree):
    """polynomial basis functions for input data x, for j=0 up to j=degree."""
    # ***************************************************
    # INSERT YOUR CODE HERE
    # polynomial basis function: TODO
    # this function should return the matrix formed
    # by applying the polynomial basis to the input data
    # ***************************************************
    return np.array([[x1 ** j for j in range(1,degree+1)] for x1 in x])
x_kek_new = build_poly(x_kek_new, 2)

In [413]:
x_kek_new = x_kek[:, good]


In [385]:
x_kek_new = x_kek_new.reshape(x_kek_new.shape[0],-1)

In [414]:
x_kek_new.shape

(328135, 224)

In [207]:
pos = sum(y_train_new == 1)
neg = len(y_train_new) - pos
print(pos,neg)


318725 299160


In [35]:
from implementations import logistic_regression

In [419]:
w, loss = logistic_regression(y_train, x_kek_new, np.zeros(x_kek_new.shape[1]), 1000, 0.1)

42
1.2819260017067629
42
1.2604847492195597
42
1.2407267649055225
42
1.222502252223195
42
1.2056762297545824
42
1.1901234835129104
42
1.1757314494043196
42
1.1623964266602196
42
1.150025283363044
42
1.1385326705720344
42
1.1278419478451924
42
1.1178831742113229
42
1.1085935256532526
42
1.0999158534037579
42
1.0917987803472549
42
1.08419566123321
42
1.0770644916160539
42
1.0703671552488017
42
1.064069241435261
42
1.0581395012062487
42
1.052549636399473
42
1.0472739071939383
42
1.042288928592395
42
1.037573385307664
42
1.0331078515232457
42
1.0288745803086015
42
1.0248573509673935
42
1.0210413099819853
42
1.017412844739953
42
1.0139594607217872
42
1.010669678312667
42
1.0075329362672505
42
1.0045395078613717
42
1.0016804240199921
42
0.9989474052940933
42
0.9963328000789621
42
0.9938295293763926
42
0.9914310367976992
42
0.989131243592991
42
0.9869245079634901
42
0.9848055883215584
42
0.982769610014579
42
0.9808120351899916
42
0.9789286354546709
42
0.9771154670541864
42
0.9753688483091666


In [426]:
y_ans = 2 * (x_orb_new @ w > 0) - 1

In [424]:
x_orb_new = x_orb[:, good]

In [427]:
sum(y_ans == 1)

33308

In [428]:
create_csv_submission(test_ids, y_ans, "meme")

In [80]:
x_kek = np.nan_to_num(x_train)

np.quantile(x_kek, 0.9,axis=1)

array([57.        ,  9.        , 54.50896475, ..., 39.        ,
       30.        , 22.81      ])

In [81]:
np.min(x_kek)

0.0

In [420]:
y_tr = 2 * (x_kek_new @ w > 0) - 1

In [421]:
np.mean(y_tr == y_train)

0.7515321437822847

In [422]:
ind = (y_train == 1)
tp = sum(y_train[ind] == y_tr[ind])
fn = sum(y_train[ind] != y_tr[ind])
ind = (y_train == -1)
tn = sum(y_train[ind] == y_tr[ind])
fp = sum(y_train[ind] != y_tr[ind])
pr = tp / (tp + fp)
rec = tp / (tp + fn)
f1 = 2 * pr * rec / (pr + rec)
print(f1)

0.36589747777596304


In [227]:
loss

0.6581132826605496